#Site Settings
title: Denis Lukianenko
email: denlyk1@gmail.com
description: motion-artist

# Build settings

markdown: kramdown
permalink: pretty
baseurl: home

port: 3000

sass:
  sass_dir: assets/css
  style: :nested
