#Site Settings
title: Denis Lukianenko
email: denlyk1@gmail.com
description: motion-artist

# Build settings

markdown: kramdown
permalink: pretty
baseurl:

port: 3000

sass:
  sass_dir: home/assets/css
  style: :nested
